
package view;

import controller.ItemFormController;
import dto.ItemDTO;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ItemForm extends javax.swing.JFrame {

    /**
     * Creates new form FoodManageForm
     */
    public ItemForm() {
        initComponents();
        table();
        mouseClickedAndReleased();
        loadAllItems();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblOrderdetailes = new javax.swing.JLabel();
        lblHome = new javax.swing.JLabel();
        lblFoodManage = new javax.swing.JLabel();
        lblOrder = new javax.swing.JLabel();
        lblCustomerDetailes = new javax.swing.JLabel();
        lblCustimerRegistration = new javax.swing.JLabel();
        pnlSet = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtItemName = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtMFD1 = new javax.swing.JTextField();
        txtEXP1 = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblManageFood = new javax.swing.JTable();
        txtItemUnitPrice = new javax.swing.JTextField();
        txtItemQty = new javax.swing.JTextField();
        txtItemCode = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 0, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/foodlogo.jpg"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 140, 160));

        lblOrderdetailes.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblOrderdetailes.setForeground(new java.awt.Color(255, 255, 255));
        lblOrderdetailes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Numbered_List_45px.png"))); // NOI18N
        lblOrderdetailes.setText("    ORDER DETAILES");
        jPanel2.add(lblOrderdetailes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 210, 70));

        lblHome.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblHome.setForeground(new java.awt.Color(255, 255, 255));
        lblHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Home_45px_1.png"))); // NOI18N
        lblHome.setText("    HOME");
        lblHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHomeMouseClicked(evt);
            }
        });
        jPanel2.add(lblHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 210, 70));

        lblFoodManage.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblFoodManage.setForeground(new java.awt.Color(255, 255, 255));
        lblFoodManage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Hamburger_45px_1.png"))); // NOI18N
        lblFoodManage.setText("    FOOD MANAGE");
        jPanel2.add(lblFoodManage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 210, 70));

        lblOrder.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblOrder.setForeground(new java.awt.Color(255, 255, 255));
        lblOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Shopping_Cart_45px.png"))); // NOI18N
        lblOrder.setText("    ORDER");
        lblOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOrderMouseClicked(evt);
            }
        });
        jPanel2.add(lblOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 210, 70));

        lblCustomerDetailes.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblCustomerDetailes.setForeground(new java.awt.Color(255, 255, 255));
        lblCustomerDetailes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_User_Account_45px_1.png"))); // NOI18N
        lblCustomerDetailes.setText("    CUSTOMER DETAILES");
        jPanel2.add(lblCustomerDetailes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 210, 70));

        lblCustimerRegistration.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblCustimerRegistration.setForeground(new java.awt.Color(255, 255, 255));
        lblCustimerRegistration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Registration_45px.png"))); // NOI18N
        lblCustimerRegistration.setText("    CUSTOMER REGISTRA");
        lblCustimerRegistration.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCustimerRegistrationMouseClicked(evt);
            }
        });
        jPanel2.add(lblCustimerRegistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 210, 70));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 720));

        pnlSet.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 0, 51));
        jLabel10.setText("DESCRIPTION");
        pnlSet.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 160, 40));

        txtItemName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtItemName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 2, true));
        txtItemName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtItemNameActionPerformed(evt);
            }
        });
        pnlSet.add(txtItemName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 250, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 0, 51));
        jLabel13.setText("UNIT PRICE");
        pnlSet.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 160, 40));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 0, 51));
        jLabel12.setText("QTY ON HAND");
        pnlSet.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 160, 40));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 0, 51));
        jLabel14.setText("EXP");
        pnlSet.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 160, 40));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 0, 51));
        jLabel11.setText("ITEM ID");
        pnlSet.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 160, 40));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 0, 51));
        jLabel15.setText("MFD");
        pnlSet.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 160, 40));

        btnSave.setBackground(new java.awt.Color(51, 0, 51));
        btnSave.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        pnlSet.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, 90, 30));

        btnUpdate.setBackground(new java.awt.Color(51, 0, 51));
        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        pnlSet.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 90, 30));

        btnDelete.setBackground(new java.awt.Color(51, 0, 51));
        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        pnlSet.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, 90, 30));

        txtMFD1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtMFD1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 2, true));
        txtMFD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMFD1ActionPerformed(evt);
            }
        });
        pnlSet.add(txtMFD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 250, 30));

        txtEXP1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtEXP1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 2, true));
        txtEXP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEXP1ActionPerformed(evt);
            }
        });
        pnlSet.add(txtEXP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 250, 30));

        btnClear.setBackground(new java.awt.Color(51, 0, 51));
        btnClear.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        pnlSet.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, 90, 30));

        tblManageFood.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ITEM ID", "DESCRIPTION", "UNIT PRICE", "QTY ON HAND", "MFD", "EXP"
            }
        ));
        jScrollPane1.setViewportView(tblManageFood);

        pnlSet.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 870, 300));

        txtItemUnitPrice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtItemUnitPrice.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 2, true));
        txtItemUnitPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtItemUnitPriceActionPerformed(evt);
            }
        });
        pnlSet.add(txtItemUnitPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 250, 30));

        txtItemQty.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtItemQty.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 2, true));
        txtItemQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtItemQtyActionPerformed(evt);
            }
        });
        pnlSet.add(txtItemQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 250, 30));

        txtItemCode.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtItemCode.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 2, true));
        txtItemCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtItemCodeActionPerformed(evt);
            }
        });
        pnlSet.add(txtItemCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 250, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 51));
        jLabel4.setText("MANAGE FOOD");
        pnlSet.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 310, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/FoodManageFormImage.png"))); // NOI18N
        pnlSet.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 720));

        jPanel1.add(pnlSet, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 1070, 720));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseClicked

    }//GEN-LAST:event_lblHomeMouseClicked

    private void txtItemNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtItemNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtItemNameActionPerformed

    private void txtItemQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtItemQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtItemQtyActionPerformed

    private void txtItemUnitPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtItemUnitPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtItemUnitPriceActionPerformed

    private void txtItemCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtItemCodeActionPerformed
      
        try {
            String itemCode = txtItemCode.getText();
             
            ItemDTO searchItem = new ItemFormController().searchItem(itemCode);
            if (searchItem != null) {
                txtItemCode.setText(searchItem.getItemCode());
                txtItemName.setText(searchItem.getItemName());
                txtItemQty.setText(searchItem.getQty()+ "");
                txtItemUnitPrice.setText(searchItem.getUnitPrice()+ "");
                txtMFD1.setText(searchItem.getmFDate());
                txtEXP1.setText(searchItem.getExDate());
                
            } else {
                clearAllText();
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ItemForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ItemForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtItemCodeActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            //SimpleDateFormat format1 = new SimpleDateFormat("yyyy-MM-dd");
            //String date1=format1.format(txtMFD.getDate());
            //SimpleDateFormat format2 = new SimpleDateFormat("yyyy-MM-dd");
            //String date2=format2.format(txtExpire.getDate());
        
        
        
        String itemCode = txtItemCode.getText();
        String itemName = txtItemName.getText();
        double unitPrice = Double.parseDouble(txtItemUnitPrice.getText());
        int qty = Integer.parseInt(txtItemQty.getText());
        
        String mFDate=txtMFD1.getText();
        String exDate=txtEXP1.getText();
        
        

            ItemDTO item = new ItemDTO(itemCode, itemName, unitPrice, qty, mFDate, exDate);
            boolean addItem = new ItemFormController().addItem(item);

            if (addItem) {
                JOptionPane.showMessageDialog(this, "Item Saved");
                loadAllItems();
            } else {
                JOptionPane.showMessageDialog(this, "Item Not Saved");
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ItemForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ItemForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        String itemCode = txtItemCode.getText();
        String itemName = txtItemName.getText();
        int qty = Integer.parseInt(txtItemQty.getText());
        double unitPrice = Double.parseDouble(txtItemUnitPrice.getText());
        String mFDate=txtMFD1.getText();
        String exDate=txtEXP1.getText();
        
        try {

            ItemDTO item = new ItemDTO(itemCode, itemName,unitPrice ,qty,mFDate,exDate);
            boolean updateItem = new ItemFormController().updateItem(item);

            if (updateItem) {
                JOptionPane.showMessageDialog(this, "Item Updated");
                loadAllItems();
            } else {
                JOptionPane.showMessageDialog(this, "Item Not Updated");
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ItemForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ItemForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        
        String itemCode = txtItemCode.getText();

        try {
            boolean result = new ItemFormController().deleteItem(itemCode);
            if (result) {
                JOptionPane.showMessageDialog(this, "Item Deleted");
                loadAllItems();
            } else {
                JOptionPane.showMessageDialog(this, "Item Not Deleted");
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ItemForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ItemForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearAllText();
    }//GEN-LAST:event_btnClearActionPerformed

    private void txtMFD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMFD1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMFD1ActionPerformed

    private void txtEXP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEXP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEXP1ActionPerformed

    private void lblCustimerRegistrationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCustimerRegistrationMouseClicked
       new CustomerForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblCustimerRegistrationMouseClicked

    private void lblOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOrderMouseClicked
         new OrderForm().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_lblOrderMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())){
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ItemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ItemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ItemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ItemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ItemForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCustimerRegistration;
    private javax.swing.JLabel lblCustomerDetailes;
    private javax.swing.JLabel lblFoodManage;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblOrder;
    private javax.swing.JLabel lblOrderdetailes;
    private javax.swing.JPanel pnlSet;
    private javax.swing.JTable tblManageFood;
    private javax.swing.JTextField txtEXP1;
    private javax.swing.JTextField txtItemCode;
    private javax.swing.JTextField txtItemName;
    private javax.swing.JTextField txtItemQty;
    private javax.swing.JTextField txtItemUnitPrice;
    private javax.swing.JTextField txtMFD1;
    // End of variables declaration//GEN-END:variables

 private void table() {
        tblManageFood.getTableHeader().setFont(new Font("Segoe UI",Font.BOLD,18));
        tblManageFood.getTableHeader().setOpaque(false);
        tblManageFood.getTableHeader().setBackground(new Color(255,255,255));
        tblManageFood.getTableHeader().setForeground(new Color(51,0,51));
        tblManageFood.setRowHeight(25);
    }

    private void mouseClickedAndReleased() {
        JLabel[] lbl={lblHome,lblCustimerRegistration,lblCustomerDetailes,lblFoodManage,lblOrder,lblOrderdetailes};
        for (JLabel jLabel : lbl) {
                jLabel.setBackground(new Color(51,0,51));
                jLabel.setOpaque(true);
                jLabel.addMouseListener(new MouseListener() {
                    @Override
                    public void mouseClicked(MouseEvent e) {
                    }
                    @Override
                    public void mousePressed(MouseEvent e) { 
                    }
                    @Override
                    public void mouseReleased(MouseEvent e) { 
                    }
                    @Override
                    public void mouseEntered(MouseEvent e) {
                       jLabel.setBackground(new Color(191, 116, 205));
                    }
                    @Override
                    public void mouseExited(MouseEvent e) {
                       jLabel.setBackground(new Color(51,0,51));
                    }
                });
        }
    }
    
     private void clearAllText() {
        txtItemCode.setText("");
        txtItemName.setText("");
        txtItemQty.setText("");
        txtItemUnitPrice.setText("");
        txtMFD1.setText("");
        txtEXP1.setText("");
        txtItemCode.requestFocus();
        loadAllItems();
    }
     
    private void loadAllItems() {

        DefaultTableModel dtm = (DefaultTableModel) tblManageFood.getModel();
        dtm.setRowCount(0);

        try {
            ArrayList<ItemDTO> allItems = new ItemFormController().getAllItems();
            for (ItemDTO i : allItems) {
                Object[] row = {i.getItemCode(), i.getItemName(), i.getQty(), i.getUnitPrice(),i.getmFDate(),i.getExDate()};
                dtm.addRow(row);
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ItemForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ItemForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


}
