/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ItemFormController;
import controller.OrderFormController;
import dto.CustomerDTO;
import dto.ItemDTO;
import dto.OrderDTO;
import dto.OrderDetailDTO;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vimukthi
 */
public class OrderForm extends javax.swing.JFrame {
//DefaultTableModel modal; 
   
     /* Creates new form OrderDetailesForm
     */
    public OrderForm() {
        initComponents();
        table();
        //modal = (DefaultTableModel) tblOrderManage1.getModel();
        mouseClickedAndReleased();
        setDate();
        loadAllCustomers();
        loadAllItems();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblOrderdetailes = new javax.swing.JLabel();
        lblHome = new javax.swing.JLabel();
        lblFoodManage = new javax.swing.JLabel();
        lblOrder = new javax.swing.JLabel();
        lblCustomerDetailes = new javax.swing.JLabel();
        lblCustimerRegistration = new javax.swing.JLabel();
        pnlSet = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtOrderDate = new javax.swing.JTextField();
        txtCusNIC = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cmbOrderSTate = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtOrderID = new javax.swing.JTextField();
        txtCusName = new javax.swing.JTextField();
        txtCusAddress = new javax.swing.JTextField();
        txtCusPhone = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtItemName = new javax.swing.JTextField();
        cmbItemID = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        txtQtyOnHand = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtUnitPrice = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtMFD = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtExp = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        cmbCusID = new javax.swing.JComboBox<>();
        txtCusSalary = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtBuyQty = new javax.swing.JTextField();
        btnAddToCart = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrderManage2 = new javax.swing.JTable();
        btnPlaceOrder = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblOrderManage1 = new javax.swing.JTable();
        btnAddToOrdertable = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNetTotal = new javax.swing.JTextField();
        btnOM2RemoveForCart = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnRemoveForCart = new javax.swing.JButton();
        txtTblNetTotal = new javax.swing.JTextField();
        txtTblOrderId = new javax.swing.JTextField();
        txtTblCustomerId = new javax.swing.JTextField();
        txtTblDate = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(1500, 800));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 0, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/foodlogo.jpg"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 140, 160));

        lblOrderdetailes.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblOrderdetailes.setForeground(new java.awt.Color(255, 255, 255));
        lblOrderdetailes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Numbered_List_45px.png"))); // NOI18N
        lblOrderdetailes.setText("    ORDER DETAILES");
        jPanel2.add(lblOrderdetailes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 210, 70));

        lblHome.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblHome.setForeground(new java.awt.Color(255, 255, 255));
        lblHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Home_45px_1.png"))); // NOI18N
        lblHome.setText("    HOME");
        lblHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHomeMouseClicked(evt);
            }
        });
        jPanel2.add(lblHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 210, 70));

        lblFoodManage.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblFoodManage.setForeground(new java.awt.Color(255, 255, 255));
        lblFoodManage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Hamburger_45px_1.png"))); // NOI18N
        lblFoodManage.setText("    FOOD MANAGE");
        lblFoodManage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFoodManageMouseClicked(evt);
            }
        });
        jPanel2.add(lblFoodManage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 210, 70));

        lblOrder.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblOrder.setForeground(new java.awt.Color(255, 255, 255));
        lblOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Shopping_Cart_45px.png"))); // NOI18N
        lblOrder.setText("    ORDER");
        jPanel2.add(lblOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 210, 70));

        lblCustomerDetailes.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblCustomerDetailes.setForeground(new java.awt.Color(255, 255, 255));
        lblCustomerDetailes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_User_Account_45px_1.png"))); // NOI18N
        lblCustomerDetailes.setText("    CUSTOMER DETAILES");
        jPanel2.add(lblCustomerDetailes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 210, 70));

        lblCustimerRegistration.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblCustimerRegistration.setForeground(new java.awt.Color(255, 255, 255));
        lblCustimerRegistration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Registration_45px.png"))); // NOI18N
        lblCustimerRegistration.setText("    CUSTOMER REGISTRA");
        lblCustimerRegistration.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCustimerRegistrationMouseClicked(evt);
            }
        });
        jPanel2.add(lblCustimerRegistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 210, 70));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 800));

        pnlSet.setBackground(java.awt.Color.white);
        pnlSet.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 51));
        jLabel4.setText("ORDER MANAGE");
        pnlSet.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 340, 60));

        txtOrderDate.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtOrderDate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 2, true));
        txtOrderDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrderDateActionPerformed(evt);
            }
        });
        pnlSet.add(txtOrderDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 100, 30));

        txtCusNIC.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtCusNIC.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 2, true));
        txtCusNIC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCusNICActionPerformed(evt);
            }
        });
        pnlSet.add(txtCusNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 120, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 0, 51));
        jLabel13.setText("ORDER ID");
        pnlSet.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, 20));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 0, 51));
        jLabel14.setText("CUTOMER ID");
        pnlSet.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, 20));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 0, 51));
        jLabel15.setText("ADDRESS");
        pnlSet.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, 20));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 0, 51));
        jLabel16.setText("PHONE");
        pnlSet.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, -1, -1));

        cmbOrderSTate.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        cmbOrderSTate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "OK", "CANCEL" }));
        cmbOrderSTate.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbOrderSTateItemStateChanged(evt);
            }
        });
        cmbOrderSTate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOrderSTateActionPerformed(evt);
            }
        });
        pnlSet.add(cmbOrderSTate, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 590, 150, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 0, 51));
        jLabel17.setText("NIC");
        pnlSet.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, 20));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 0, 51));
        jLabel18.setText("NAME");
        pnlSet.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, -1, 20));

        txtOrderID.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtOrderID.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 2, true));
        txtOrderID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrderIDActionPerformed(evt);
            }
        });
        pnlSet.add(txtOrderID, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 100, 30));

        txtCusName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtCusName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 2, true));
        txtCusName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCusNameActionPerformed(evt);
            }
        });
        pnlSet.add(txtCusName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 120, 30));

        txtCusAddress.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtCusAddress.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 2, true));
        txtCusAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCusAddressActionPerformed(evt);
            }
        });
        pnlSet.add(txtCusAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 120, 30));

        txtCusPhone.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtCusPhone.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 2, true));
        txtCusPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCusPhoneActionPerformed(evt);
            }
        });
        pnlSet.add(txtCusPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 120, 30));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 0, 51));
        jLabel19.setText("ITEM CODE");
        pnlSet.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, 20));

        txtItemName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtItemName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 2, true));
        txtItemName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtItemNameActionPerformed(evt);
            }
        });
        pnlSet.add(txtItemName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, 120, 30));

        cmbItemID.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        cmbItemID.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbItemIDItemStateChanged(evt);
            }
        });
        cmbItemID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbItemIDActionPerformed(evt);
            }
        });
        pnlSet.add(cmbItemID, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 150, 30));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 0, 51));
        jLabel21.setText("QTY ON HAND");
        pnlSet.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, -1, 20));

        txtQtyOnHand.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtQtyOnHand.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 2, true));
        txtQtyOnHand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtyOnHandActionPerformed(evt);
            }
        });
        pnlSet.add(txtQtyOnHand, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 120, 30));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(51, 0, 51));
        jLabel29.setText("ORDER TABLE ID");
        pnlSet.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 600, -1, 20));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 0, 51));
        jLabel22.setText("UNIT PRICE");
        pnlSet.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 490, -1, -1));

        txtUnitPrice.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtUnitPrice.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 2, true));
        txtUnitPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnitPriceActionPerformed(evt);
            }
        });
        pnlSet.add(txtUnitPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 510, 120, 30));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 0, 51));
        jLabel23.setText("MFD");
        pnlSet.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, -1, 20));

        txtMFD.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtMFD.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 2, true));
        txtMFD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMFDActionPerformed(evt);
            }
        });
        pnlSet.add(txtMFD, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 570, 120, 30));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 0, 51));
        jLabel24.setText("EXP");
        pnlSet.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 550, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 0, 51));
        jLabel11.setText("ORDER DATE");
        pnlSet.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, -1));

        txtExp.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtExp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 2, true));
        txtExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExpActionPerformed(evt);
            }
        });
        pnlSet.add(txtExp, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 570, 120, 30));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlSet.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 280, 80));

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(51, 0, 51));
        jLabel27.setText("SALARY");
        jPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, -1, 20));

        cmbCusID.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        cmbCusID.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCusIDItemStateChanged(evt);
            }
        });
        cmbCusID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCusIDActionPerformed(evt);
            }
        });
        jPanel4.add(cmbCusID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 150, 30));

        txtCusSalary.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtCusSalary.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 2, true));
        txtCusSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCusSalaryActionPerformed(evt);
            }
        });
        jPanel4.add(txtCusSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 120, 30));

        pnlSet.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 340, 200));

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 0, 51));
        jLabel20.setText("DESCRIPTION");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, 20));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(51, 0, 51));
        jLabel28.setText("BUY QTY");
        jPanel5.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, 20));

        txtBuyQty.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtBuyQty.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 2, true));
        txtBuyQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuyQtyActionPerformed(evt);
            }
        });
        jPanel5.add(txtBuyQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 120, 30));

        btnAddToCart.setBackground(new java.awt.Color(51, 0, 51));
        btnAddToCart.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnAddToCart.setForeground(new java.awt.Color(255, 255, 255));
        btnAddToCart.setText("ADD TO CART");
        btnAddToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddToCartActionPerformed(evt);
            }
        });
        jPanel5.add(btnAddToCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 120, 30));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 180, 80));

        pnlSet.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 340, 270));

        tblOrderManage2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        tblOrderManage2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ORDER ID", "CUSTOMER ID", "DATE", "NET TOTAL"
            }
        ));
        tblOrderManage2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblOrderManage2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblOrderManage2);

        pnlSet.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, 630, 220));

        btnPlaceOrder.setBackground(new java.awt.Color(51, 0, 51));
        btnPlaceOrder.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnPlaceOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnPlaceOrder.setText("PLACE ORDER");
        btnPlaceOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaceOrderActionPerformed(evt);
            }
        });
        pnlSet.add(btnPlaceOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 420, 160, 30));

        tblOrderManage1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        tblOrderManage1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ORDER ID", "ITEM CODE", "DESCRIPTION", "BUY QTY", "UNIT PRICE", "TOTAL"
            }
        ));
        jScrollPane2.setViewportView(tblOrderManage1);

        pnlSet.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 630, 180));

        btnAddToOrdertable.setBackground(new java.awt.Color(51, 0, 51));
        btnAddToOrdertable.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnAddToOrdertable.setForeground(new java.awt.Color(255, 255, 255));
        btnAddToOrdertable.setText("ADD TO ORDER TABLE");
        btnAddToOrdertable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddToOrdertableActionPerformed(evt);
            }
        });
        pnlSet.add(btnAddToOrdertable, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 110, 180, 30));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 0, 51));
        jLabel25.setText("CUSTOMER ID");
        pnlSet.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, -1, 20));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 0, 51));
        jLabel26.setText("BUY QTY");
        pnlSet.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 550, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 0));
        jLabel1.setText("NET TOTAL");
        pnlSet.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, -1, -1));

        txtNetTotal.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtNetTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0), 2));
        txtNetTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNetTotalActionPerformed(evt);
            }
        });
        pnlSet.add(txtNetTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, 130, 30));

        btnOM2RemoveForCart.setBackground(new java.awt.Color(51, 0, 51));
        btnOM2RemoveForCart.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnOM2RemoveForCart.setForeground(new java.awt.Color(255, 255, 255));
        btnOM2RemoveForCart.setText("REMOVE FOR CART");
        btnOM2RemoveForCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOM2RemoveForCartActionPerformed(evt);
            }
        });
        pnlSet.add(btnOM2RemoveForCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 350, 160, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 51));
        jLabel3.setText("ORDER TABLE");
        pnlSet.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, -1, -1));

        btnRemoveForCart.setBackground(new java.awt.Color(51, 0, 51));
        btnRemoveForCart.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnRemoveForCart.setForeground(new java.awt.Color(255, 255, 255));
        btnRemoveForCart.setText("REMOVE FOR CART");
        btnRemoveForCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveForCartActionPerformed(evt);
            }
        });
        pnlSet.add(btnRemoveForCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 50, 170, 30));

        txtTblNetTotal.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtTblNetTotal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 2, true));
        txtTblNetTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTblNetTotalActionPerformed(evt);
            }
        });
        pnlSet.add(txtTblNetTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 740, 120, 30));

        txtTblOrderId.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtTblOrderId.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 2, true));
        txtTblOrderId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTblOrderIdActionPerformed(evt);
            }
        });
        pnlSet.add(txtTblOrderId, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 590, 120, 30));

        txtTblCustomerId.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtTblCustomerId.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 2, true));
        txtTblCustomerId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTblCustomerIdActionPerformed(evt);
            }
        });
        pnlSet.add(txtTblCustomerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 640, 120, 30));

        txtTblDate.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtTblDate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 2, true));
        txtTblDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTblDateActionPerformed(evt);
            }
        });
        pnlSet.add(txtTblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 690, 120, 30));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(51, 0, 51));
        jLabel30.setText("ORDER STATE");
        pnlSet.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 590, -1, 20));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(51, 0, 51));
        jLabel31.setText("NET TOTAL");
        pnlSet.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 750, -1, 20));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(51, 0, 51));
        jLabel32.setText("DATE");
        pnlSet.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 700, -1, 20));

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(51, 0, 51));
        jLabel33.setText("CUSTOMER ID");
        pnlSet.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 650, -1, 20));

        btnSave.setBackground(new java.awt.Color(51, 0, 51));
        btnSave.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        pnlSet.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 660, 150, 30));

        jButton1.setBackground(new java.awt.Color(51, 0, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("CLEAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pnlSet.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 170, -1, -1));

        jPanel1.add(pnlSet, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 1290, 800));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseClicked

    }//GEN-LAST:event_lblHomeMouseClicked

    private void txtOrderDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrderDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrderDateActionPerformed

    private void txtCusNICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCusNICActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCusNICActionPerformed

    private void cmbCusIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCusIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCusIDActionPerformed

    private void txtOrderIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrderIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrderIDActionPerformed

    private void txtCusNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCusNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCusNameActionPerformed

    private void txtCusAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCusAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCusAddressActionPerformed

    private void txtCusPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCusPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCusPhoneActionPerformed

    private void txtItemNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtItemNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtItemNameActionPerformed

    private void cmbItemIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbItemIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbItemIDActionPerformed

    private void txtQtyOnHandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtyOnHandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtyOnHandActionPerformed

    private void txtUnitPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnitPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnitPriceActionPerformed

    private void txtMFDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMFDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMFDActionPerformed

    private void txtExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExpActionPerformed

    private void btnPlaceOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceOrderActionPerformed
       /* String oid=txtOrderId.getText();
        String date= txtDate.getText();
        String cusId=cmbCustomerid.getSelectedItem().toString();
        
        ArrayList<OrderDetail> list= new ArrayList();
        
        DefaultTableModel modal= (DefaultTableModel) tbl.getModel();
        
        for (int i = 0; i < modal.getRowCount(); i++) {
            list.add(new OrderDetail(
                    oid, 
                    (String)modal.getValueAt(i,0),
                    (int)modal.getValueAt(i, 2),
                    (double)modal.getValueAt(i, 3)
            ));
        }
        
        
        Order oder= new Order(oid, date, cusId, list);
        
        boolean isSaved=new OrderController().saveOrder(oder);
        
        if(isSaved){
            JOptionPane.showMessageDialog(this, "Saved");
        }else{
            JOptionPane.showMessageDialog(this, "Try Again");
        } */
        
        
        try {
           DefaultTableModel modal = (DefaultTableModel) tblOrderManage1.getModel();
            String orderID = txtOrderID.getText();
            String orderDate = txtOrderDate.getText();
            String customerID = cmbCusID.getSelectedItem().toString();

            OrderDTO order = new OrderDTO(orderID, orderDate, customerID);


            for (int i = 0; i < modal.getRowCount(); i++) {

                String itemCode = modal.getValueAt(i, 1).toString();
                int qty = Integer.parseInt(modal.getValueAt(i, 3).toString());
                double unitPrice = Double.parseDouble(modal.getValueAt(i, 4).toString());

                OrderDetailDTO orderDetail = new OrderDetailDTO(orderID, itemCode, qty, unitPrice);
                order.getOrderDetails().add(orderDetail);
            }

           
            boolean purchaseOrder = new OrderFormController().purchaseOrder(order);
            if (purchaseOrder) {
                JOptionPane.showMessageDialog(this, "Save Order");
            } else {
                JOptionPane.showMessageDialog(this, "Not Save Order");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(OrderForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(OrderForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPlaceOrderActionPerformed

    private void btnAddToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToCartActionPerformed
        String oid=txtOrderID.getText();
        String code =cmbItemID.getSelectedItem().toString();
        String name=txtItemName.getText();
        int qty = Integer.parseInt(txtBuyQty.getText());
        double unitPrice = Double.parseDouble(txtUnitPrice.getText());
        double total = qty * unitPrice;

        DefaultTableModel modal = (DefaultTableModel) tblOrderManage1.getModel();

        int rowNumber = isAlreadyExists(cmbItemID.getSelectedItem().toString());

        if (rowNumber == -1) {
            Object[] rowData = {oid,code,name,qty,unitPrice,total};
            modal.addRow(rowData);
        }else{
            qty+=(int)modal.getValueAt(rowNumber, 3);
            total=qty*unitPrice;
            tblOrderManage1.setValueAt(qty, rowNumber, 3);
            tblOrderManage1.setValueAt(total, rowNumber, 5);
        }

        
        calculate(modal);
    }//GEN-LAST:event_btnAddToCartActionPerformed

    private void btnAddToOrdertableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToOrdertableActionPerformed
        DefaultTableModel modal1=(DefaultTableModel) tblOrderManage2.getModel();
        
        String oId = txtOrderID.getText();
        String cusId=cmbCusID.getSelectedItem().toString();
        String date=txtOrderDate.getText();
        String netTotal=txtNetTotal.getText();
        
        Object[] row = {oId, cusId, date, netTotal};
        modal1.addRow(row);
    }//GEN-LAST:event_btnAddToOrdertableActionPerformed

    private void txtNetTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNetTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNetTotalActionPerformed

    private void btnOM2RemoveForCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOM2RemoveForCartActionPerformed
        int rowId = tblOrderManage2.getSelectedRow();

        if (rowId == -1) {
            return;
        }
        DefaultTableModel modal2 = (DefaultTableModel) tblOrderManage2.getModel();
        modal2.removeRow(rowId);
    }//GEN-LAST:event_btnOM2RemoveForCartActionPerformed

    private void btnRemoveForCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveForCartActionPerformed
        int rowId = tblOrderManage1.getSelectedRow();

        if (rowId == -1) {
            return;
        }
        DefaultTableModel modal = (DefaultTableModel) tblOrderManage1.getModel();
        modal.removeRow(rowId);
    }//GEN-LAST:event_btnRemoveForCartActionPerformed

    private void cmbCusIDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCusIDItemStateChanged
        txtNetTotal.setText("");
        try {
            String selectedCustomerID = cmbCusID.getSelectedItem().toString();
            CustomerDTO searchCustomer = new OrderFormController().searchCustomer(selectedCustomerID);
            if (searchCustomer != null) {
                txtCusName.setText(searchCustomer.getCustomerName());
                txtCusAddress.setText(searchCustomer.getCustomerAddress());
                txtCusPhone.setText(searchCustomer.getCustomerPhone());
                txtCusNIC.setText(searchCustomer.getCustomerNIC());
                txtCusSalary.setText(searchCustomer.getCustomerSalary()+ "");
            }

        } catch (SQLException ex) {
            Logger.getLogger(OrderForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(OrderForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbCusIDItemStateChanged

    private void txtTblNetTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTblNetTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTblNetTotalActionPerformed

    private void txtBuyQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuyQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuyQtyActionPerformed

    private void cmbItemIDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbItemIDItemStateChanged
        txtBuyQty.setText("");
        String selectedItem = cmbItemID.getSelectedItem().toString();
        try {
            ItemDTO searchItem = new OrderFormController().searchItem(selectedItem);
            if (searchItem != null) {
                txtItemName.setText(searchItem.getItemName());
                txtQtyOnHand.setText(searchItem.getQty() + "");
                txtUnitPrice.setText(searchItem.getUnitPrice() + "");
                txtMFD.setText(searchItem.getmFDate());
                txtExp.setText(searchItem.getExDate());
            }

        } catch (SQLException ex) {
            Logger.getLogger(OrderForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(OrderForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbItemIDItemStateChanged

    private void cmbOrderSTateItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbOrderSTateItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbOrderSTateItemStateChanged

    private void cmbOrderSTateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOrderSTateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbOrderSTateActionPerformed

    private void txtCusSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCusSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCusSalaryActionPerformed

    private void txtTblOrderIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTblOrderIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTblOrderIdActionPerformed

    private void txtTblCustomerIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTblCustomerIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTblCustomerIdActionPerformed

    private void txtTblDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTblDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTblDateActionPerformed

    private void tblOrderManage2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblOrderManage2MouseClicked
       int selectedRow = tblOrderManage2.getSelectedRow();
       DefaultTableModel model = (DefaultTableModel) tblOrderManage2.getModel();   
        
       txtTblOrderId.setText(model.getValueAt(selectedRow, 0).toString());
       txtTblCustomerId.setText(model.getValueAt(selectedRow, 1).toString());
       txtTblDate.setText(model.getValueAt(selectedRow, 2).toString());
       txtTblNetTotal.setText(model.getValueAt(selectedRow, 3).toString());
       txtTblNetTotal.setText(model.getValueAt(selectedRow, 4).toString());
    }//GEN-LAST:event_tblOrderManage2MouseClicked

    private void lblCustimerRegistrationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCustimerRegistrationMouseClicked
       new CustomerForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblCustimerRegistrationMouseClicked

    private void lblFoodManageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFoodManageMouseClicked
       new ItemForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblFoodManageMouseClicked

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
       
    }//GEN-LAST:event_btnSaveActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        DefaultTableModel modal1 = (DefaultTableModel) tblOrderManage1.getModel();
        int rowCount = modal1.getRowCount();
        
        for (int i = rowCount-1; i >= 0; i--) {
            modal1.removeRow(i);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddToCart;
    private javax.swing.JButton btnAddToOrdertable;
    private javax.swing.JButton btnOM2RemoveForCart;
    private javax.swing.JButton btnPlaceOrder;
    private javax.swing.JButton btnRemoveForCart;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbCusID;
    private javax.swing.JComboBox<String> cmbItemID;
    private javax.swing.JComboBox<String> cmbOrderSTate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCustimerRegistration;
    private javax.swing.JLabel lblCustomerDetailes;
    private javax.swing.JLabel lblFoodManage;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblOrder;
    private javax.swing.JLabel lblOrderdetailes;
    private javax.swing.JPanel pnlSet;
    private javax.swing.JTable tblOrderManage1;
    private javax.swing.JTable tblOrderManage2;
    private javax.swing.JTextField txtBuyQty;
    private javax.swing.JTextField txtCusAddress;
    private javax.swing.JTextField txtCusNIC;
    private javax.swing.JTextField txtCusName;
    private javax.swing.JTextField txtCusPhone;
    private javax.swing.JTextField txtCusSalary;
    private javax.swing.JTextField txtExp;
    private javax.swing.JTextField txtItemName;
    private javax.swing.JTextField txtMFD;
    private javax.swing.JTextField txtNetTotal;
    private javax.swing.JTextField txtOrderDate;
    private javax.swing.JTextField txtOrderID;
    private javax.swing.JTextField txtQtyOnHand;
    private javax.swing.JTextField txtTblCustomerId;
    private javax.swing.JTextField txtTblDate;
    private javax.swing.JTextField txtTblNetTotal;
    private javax.swing.JTextField txtTblOrderId;
    private javax.swing.JTextField txtUnitPrice;
    // End of variables declaration//GEN-END:variables
private void table() {
        tblOrderManage2.getTableHeader().setFont(new Font("Segoe UI",Font.BOLD,15));
        tblOrderManage2.getTableHeader().setOpaque(false);
        tblOrderManage2.getTableHeader().setBackground(new Color(255,255,255));
        tblOrderManage2.getTableHeader().setForeground(new Color(51,0,51));
        tblOrderManage2.setRowHeight(25);
        
        tblOrderManage1.getTableHeader().setFont(new Font("Segoe UI",Font.BOLD,15));
        tblOrderManage1.getTableHeader().setOpaque(false);
        tblOrderManage1.getTableHeader().setBackground(new Color(255,255,255));
        tblOrderManage1.getTableHeader().setForeground(new Color(51,0,51));
        tblOrderManage1.setRowHeight(25);
    }

    private void mouseClickedAndReleased() {
        JLabel[] lbl={lblHome,lblCustimerRegistration,lblCustomerDetailes,lblFoodManage,lblOrder,lblOrderdetailes};
        for (JLabel jLabel : lbl) {
                jLabel.setBackground(new Color(51,0,51));
                jLabel.setOpaque(true);
                jLabel.addMouseListener(new MouseListener() {
                    @Override
                    public void mouseClicked(MouseEvent e) {
                    }
                    @Override
                    public void mousePressed(MouseEvent e) { 
                    }
                    @Override
                    public void mouseReleased(MouseEvent e) { 
                    }
                    @Override
                    public void mouseEntered(MouseEvent e) {
                       jLabel.setBackground(new Color(191, 116, 205));
                    }
                    @Override
                    public void mouseExited(MouseEvent e) {
                       jLabel.setBackground(new Color(51,0,51));
                    }
                });
        }
    }
    
    private void setDate() {
        String date = LocalDate.now().toString();
        txtOrderDate.setText(date);
    }
    
     private void loadAllCustomers() {
        try {
            ArrayList<CustomerDTO> allCustomers = new OrderFormController().getAllCustomers();
            cmbCusID.removeAllItems();
            for (CustomerDTO customer : allCustomers) {
                cmbCusID.addItem(customer.getCustomerID());
            }
        } catch (SQLException ex) {
            Logger.getLogger(OrderForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(OrderForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadAllItems() {
        cmbItemID.removeAllItems();
        try {
            ArrayList<ItemDTO> allItems = new ItemFormController().getAllItems();
            for (ItemDTO item : allItems) {
                cmbItemID.addItem(item.getItemCode());
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(OrderForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(OrderForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private int isAlreadyExists(String code) {
        DefaultTableModel modal = (DefaultTableModel) tblOrderManage1.getModel();

        for (int i = 0; i < modal.getRowCount(); i++) {
            String temp = (String) modal.getValueAt(i, 1);
            if (temp.equals(code)) {
                return i;
            }
        }

        return -1;

    }
    
    private void calculate(DefaultTableModel modal) {
       double nettotal=0;
        for (int i = 0; i < modal.getRowCount(); i++) {
            nettotal+=(double)modal.getValueAt(i, 5);
        }
        
       txtNetTotal.setText(nettotal+"");
    }

}
